// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          int64
	Title       string
	Body        string
	PublishedAt pgtype.Timestamptz
}

type Author struct {
	ID   int64
	Name string
}
